---
- name: ensure var dir exists
  file:
    path: "{{ webserver.var_dir }}"
    state: directory

- name: ensure var dir is writable
  acl:
    path: "{{ webserver.var_dir }}"
    entity: "{{ item[0] }}"
    etype: user
    permissions: "rwx"
    state: present
    recursive: true
    default: "{{ item[1] }}"
  with_nested:
    - ["{{ ansible_user_id }}", "www-data"]
    - [false, true]
