imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   pdo_sqlite
        dbname:   "%database_name%"
        #memory:   true
        path:     "/dev/shm/var/test.db3"
        charset:  UTF8
        types:
            uuid: 'Ramsey\Uuid\Doctrine\UuidType'
