# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.adapter.chess_adapter:
        class: AppBundle\Adapter\ChessAdapter
        arguments: ['@chessphp.chess']

    app.import.pgn_string_importer:
        class: AppBundle\Factory\GameFactory
        arguments: ['@app.adapter.chess_adapter']

    app.entity_repository.user_repository:
        class: AppBundle\Entity\Repository\UserRepository
        factory: ['@doctrine', getRepository]
        arguments: [AppBundle\Entity\User]

    app.form.moves_type:
        class: AppBundle\Form\MovesType
        arguments: ['@app.form_data_transformer.moves_transformer']
        tags:
            - { name: form.type, alias: AppBundle\Form\MovesType }

    app.form.game_player_type:
        class: AppBundle\Form\GamePlayerType
        arguments: ['@security.token_storage', '@app.entity_repository.user_repository']
        tags:
            - { name: form.type, alias: AppBundle\Form\GamePlayerType }

    app.form_data_transformer.moves_transformer:
        class: AppBundle\Form\DataTransformer\MovesTransformer
        arguments: ['@app.helper.move_transform_helper']

    app.helper.move_transform_helper:
        class: AppBundle\Helper\MovesTransformHelper

    app.helper.registration_helper:
        class: AppBundle\Helper\RegistrationHelper
        arguments:
          - '@security.encoder_factory.generic'
          - '@app.entity_repository.user_repository'

    app.validator_constraints.pgn_validator:
        class: AppBundle\Validator\Constraints\PgnValidator
        arguments: ['@app.adapter.chess_adapter']
        tags:
            - { name: validator.constraint_validator }

    chessphp.chess:
        class: Ryanhs\Chess\Chess



    dropbox.app.info:
        class: Dropbox\AppInfo
        arguments:
            - '%dropbox_api_key%'
            - '%dropbox_api_secret%'

    app.dropbox.auth_token_store:
        class: AppBundle\Dropbox\AuthTokenStore
        arguments:
            - '@session'

    app.dropbox.auth_helper:
        class: AppBundle\Dropbox\AuthHelper
        arguments:
            - '@router'
            - '@dropbox.app.info'
            - '@app.dropbox.auth_token_store'
            - '%dropbox_app_name%'
            - 'app_dropbox_authfinish'
            - '@app.dropbox.access_token_store'

    app.dropbox.access_token_store:
        class: AppBundle\Dropbox\AccessTokenStore
        arguments:
            - '@session'
#
#    app.dropbox.client_creator:
#        class: AppBundle\Dropbox\ClientCreator
#        arguments:
#            - '@app.dropbox.token_storage'
#            - '%dropbox_app_name%'

#    app.dropbox.client:
#        class: AppBundle\Dropbox\Client
#        factory: ['@app.dropbox.client_creator', createClient]
