working_directory: symfony
global_exclude_dirs:
    - vendor
    - vendors
    - test
    - tests
    - Tests
    - lib/vendor
    - ansible
    - symfony/vendor
    - symfony/node_modules

exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app_*.php

