---
language: php
php:
  - '7.0'


before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - php app/console app:fixtures --env=test

script:
  - make test
  - make qa

notifications:
  email:
    - entengelb@gmail.com