---
language: php
php:
  - '7.0'


before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - make composer-install
  - make reset-database

script:
  - make test
  - make qa

notifications:
  email:
    - entengelb@gmail.com
