---
language: php
php:
  - '7.0'

before_script:
  - composer global require squizlabs/php_codesniffer
  - composer global require sensiolabs/security-checker
  - composer global require phpmd/phpmd
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - make composer-install
  - make reset-database

script:
  - make test
  - make qa

notifications:
  email:
    - entengelb@gmail.com
