# dev env
---
webserver:
  config_user: vagrant
  config_home: /home/vagrant
  nginx: true
  nodejs: false
  app: true
  mysql: true
  tools: false
  php_ini:
    - "error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT"
    - "display_errors=Off"
    - "date.timezone={{ php_timezone|default('Europe/Berlin') }}"
